# image and docs: https://hub.docker.com/_/odoo

version: '3.8'

services:
  odoo:
    image: odoo:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - ${APP_PORT}:8069
    volumes:
      - odoo:/var/lib/odoo
      - ${VOLUMES_PATH_PREFIX}/odoo/config:/etc/odoo
      - ${VOLUMES_PATH_PREFIX}/odoo/addons:/mnt/extra-addons
    environment:
      HOST: db
      USER: ${DB_POSTGRES_USER}
      PASSWORD: ${DB_POSTGRES_PASSWORD}
    depends_on:
      - db
    restart: always
    stdin_open: true
    tty: true

  db:
    image: postgres:${DB_POSTGRES_VERSION}
    container_name: ${APP_CONTAINER_NAME}-postgres
    restart: always
    ports:
     - ${DB_POSTGRES_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_POSTGRES_NAME}
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: --data-checksums
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data

networks:
  default:
      name: ${APP_NETWORK}

volumes:
  odoo:
  postgres: