# image: https://hub.docker.com/_/odoo
# docs: https://github.com/odoo/docker

version: '3.8'

services:
  odoo:
    image: odoo:${APP_VERSION}
    container_name: ${APP_NAME}
    ports:
      - ${APP_PORT}:8069
    volumes:
      - odoo_web:/var/lib/odoo
      - odoo_config:/etc/odoo
      - odoo_addons:/mnt/extra-addons
    environment:
      HOST: db
      USER: ${DB_POSTGRES_USER}
      PASSWORD: ${DB_POSTGRES_PASSWORD}
    user: root
    command: bash -c "cat /my_cmd > cmd.sh && chmod +x /cmd.sh && /cmd.sh"
    depends_on:
      - db
    restart: always
    configs:
      - source: my_cmd

  db:
    image: postgres:${DB_POSTGRES_VERSION}
    container_name: ${APP_NAME}-db
    restart: always
    ports:
     - ${DB_POSTGRES_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_POSTGRES_NAME}
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: --data-checksums
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data

volumes:
  odoo_web:
  odoo_config:
  odoo_addons:
  postgres:

networks:
  default:
      name: ${APP_NAME}

configs:
  my_cmd:
    file: ./cmd.sh
